name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.3.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: npm ci
    - name: Test
      run: npm run test
    - name: Fix Coverage Paths
      working-directory: ./coverage
      run: |
        sed -i 's/\/home\/runner\/work\/madoc-component-repl\/madoc-component-repl\//\/github\/workspace\//g' lcov.info
        sed -i 's/\/home\/runner\/work\/madoc-component-repl\/madoc-component-repl\//\/github\/workspace\//g' clover.xml
    - name: Sonar
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build
      run: npm run build
    - name: Publish
      run: |
        LATEST=`npm view . version`
        CURRENT=`cat package.json | jq -r .version`
        if [ "$LATEST" != "$CURRENT" ]
        then
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Domain
      run: echo "madoc-component-repl.cadgerfeast.dev" > "./.docs/CNAME"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./.docs
